version: '3'

services:
  app:
    image: demo-docker
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/app
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://localhost:3306/presupuestos_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false",
            "spring.datasource.username" : "henny",
            "spring.datasource.password" : "feferrefe2020",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'